/* ──────────────────────────────────────────
   src/utils/constants.js
   Central config — weights, verdicts, signal metadata
   ────────────────────────────────────────── */

/**
 * Signal weights — must sum to 1.0
 * HF signal weighted highest (fine-tuned model)
 */
export const WEIGHTS = {
  mobilenet:   0.08,
  frequency:   0.08,
  color:       0.06,
  edge:        0.06,
  texture:     0.05,
  noise:       0.05,
  metadata:    0.12,  // EXIF/software tag analysis
  huggingface: 0.50,  // Primary — fine-tuned model
};

/**
 * Verdict tiers based on final score
 */
export const VERDICT = [
  {
    min: 0,
    max: 34,
    label: 'LIKELY REAL',
    color: '#30d158',
    confidence: 'Medium',
    description: 'Strong indicators of a genuine photograph. Sensor noise and frequency patterns match real-world image statistics.',
  },
  {
    min: 35,
    max: 54,
    label: 'UNCERTAIN',
    color: '#ffd60a',
    confidence: 'Low',
    description: 'Mixed signals detected. Could be heavily edited, composited, or lightly AI-assisted.',
  },
  {
    min: 55,
    max: 79,
    label: 'LIKELY AI',
    color: '#ff9500',
    confidence: 'Medium',
    description: 'Multiple generative model signatures detected across several signals.',
  },
  {
    min: 80,
    max: 100,
    label: 'AI GENERATED',
    color: '#ff3b5c',
    confidence: 'High',
    description: 'High confidence this image was synthetically generated by a GAN or diffusion model.',
  },
];

/**
 * Signal metadata for UI rendering
 * icon: Unicode glyph used in DimensionCard
 */
export const SIGNAL_META = [
  {
    key: 'mobilenet',
    label: 'Embedding Anomaly',
    icon: '◈',
    description: 'MobileNet v2 embedding analysis — AI images cluster in different regions of learned feature space.',
  },
  {
    key: 'frequency',
    label: 'Frequency Artifacts',
    icon: '⬡',
    description: 'FFT spectrum analysis — GANs leave periodic grid patterns in the frequency domain.',
  },
  {
    key: 'color',
    label: 'Color Distribution',
    icon: '◉',
    description: 'AI images have unnaturally narrow color variance and smoother histograms than real photos.',
  },
  {
    key: 'edge',
    label: 'Edge Uniformity',
    icon: '▣',
    description: 'Sobel filter edge analysis — diffusion models produce unnaturally uniform or over-sharpened edges.',
  },
  {
    key: 'texture',
    label: 'Texture Regularity',
    icon: '⬟',
    description: 'Local Binary Pattern analysis — AI textures repeat with unnatural regularity.',
  },
  {
    key: 'noise',
    label: 'Noise Fingerprint',
    icon: '◇',
    description: 'Residual noise analysis — AI images lack the structured sensor noise (PRNU) of real cameras.',
  },
  {
    key: 'metadata',
    label: 'Metadata Signal',
    icon: '◑',
    description: 'EXIF metadata analysis — detects AI generator software tags and validates real camera fields.',
  },
  {
    key: 'huggingface',
    label: 'AI Model Scan',
    icon: '⬢',
    description: 'Fine-tuned deep learning model via Hugging Face — trained specifically to detect AI-generated images.',
  },
];

/**
 * Get score color based on numeric value
 */
export function getScoreColor(score) {
  if (score >= 80) return '#ff3b5c';
  if (score >= 55) return '#ff9500';
  if (score >= 35) return '#ffd60a';
  return '#30d158';
}
